linters-settings:
  errcheck:
    # List of functions to exclude from checking, where each entry is a single function to exclude.
    # See https://github.com/kisielk/errcheck#excluding-functions for details.
    exclude-functions:
      - (*terraform-provider-ome/clients.Client).RemoveSession
      - (net/http.ResponseWriter).Write
  revive:
    rules:
      - name: unused-parameter
        severity: warning
        disabled: true
      - name: var-declaration
        severity: warning
        disabled: true
      - name: exported
        disabled: false

# enable revive linter
linters:
  enable:
    - revive

issues:
  include:
    - EXC0012  # EXC0012 revive: Annoying issue about not having a comment. The rare codebase has such comments
    - EXC0014  # EXC0014 revive: Annoying issue about not having a comment. The rare codebase has such comments