linters-settings:
  errcheck:
    # List of functions to exclude from checking, where each entry is a single function to exclude.
    # See https://github.com/kisielk/errcheck#excluding-functions for details.
    exclude-functions:
      - (*terraform-provider-ome/clients.Client).RemoveSession
      - (net/http.ResponseWriter).Write